import { Zap, ArrowDownToDot } from "lucide-react"
import { PricingSection } from "@/components/blocks/pricing-section"
import { Header } from "@/components/ui/header-2"
import { Footerdemo } from "@/components/blocks/footer-section"

const defaultTiers = [
    {
        name: "Starter",
        price: {
            monthly: 499,
            yearly: 4999,
        },
        description: "Everything you need to kickstart your fitness journey",
        icon: (
            <div className="relative">
                <div className="absolute inset-0 bg-gradient-to-r from-gray-500/30 to-gray-500/30 blur-2xl rounded-full" />
                <Zap className="w-7 h-7 relative z-10 text-gray-500 animate-[float_3s_ease-in-out_infinite]" />
            </div>
        ),
        features: [
            {
                name: "AI Meal Scanning",
                description: "Log up to 15 meals per day using your camera",
                included: true,
            },
            {
                name: "Smart Insights",
                description: "Basic feedback on your daily calorie intake",
                included: true,
            },
            {
                name: "Community Access",
                description: "Connect with other NutriLife users",
                included: true,
            },
            {
                name: "Custom Diet Plans",
                description: "Personalized meals generated by our AI engine",
                included: false,
            },
        ],
    },
    {
        name: "Pro",
        price: {
            monthly: 999,
            yearly: 9999,
        },
        description: "Optimal performance for serious health enthusiasts",
        highlight: true,
        badge: "Most Popular",
        icon: (
            <div className="relative">
                <ArrowDownToDot className="w-7 h-7 relative z-10" />
            </div>
        ),
        features: [
            {
                name: "Unlimited Meal Scanning",
                description: "Snap and log every bite, no limits",
                included: true,
            },
            {
                name: "AI Diet Plans",
                description: "Full-scale customized weekly nutritional plans",
                included: true,
            },
            {
                name: "Priority Support",
                description: "Get answers from nutritionists in under 12 hours",
                included: true,
            },
            {
                name: "Advanced Analytics",
                description: "Deep dive into macro trends and health auditing",
                included: true,
            },
        ],
    },
]

export function PricingPage() {
    return (
        <div className="min-h-screen bg-background text-foreground flex flex-col font-sans">
            <Header />
            <main className="flex-1 flex flex-col pt-12 px-4 container mx-auto max-w-6xl pb-20 animate-in fade-in zoom-in-95 duration-500" style={{ marginTop: "-50px" }}>
                <PricingSection tiers={defaultTiers} />
            </main>
            <Footerdemo />
        </div>
    )
}
