# Generated by Django 6.0.3 on 2026-03-07 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_exercisebalance_foodswap_meal_analysis_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='sugar',
            field=models.FloatField(default=0),
        ),
    ]
