# Generated by Django 6.0.3 on 2026-03-07 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_meal_sugar'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='contains_refined_flour',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='meal',
            name='is_fried',
            field=models.BooleanField(default=False),
        ),
    ]
