# Generated by Django 6.0.3 on 2026-03-07 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_meal_contains_refined_flour_meal_is_fried'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='cholesterol',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='meal',
            name='fiber',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='meal',
            name='sodium',
            field=models.FloatField(default=0),
        ),
    ]
