# Generated by Django 6.0.3 on 2026-03-07 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_meal_cholesterol_meal_fiber_meal_sodium'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='is_processed',
            field=models.BooleanField(default=False),
        ),
    ]
