# Generated by Django 6.0.3 on 2026-03-07 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_meal_is_processed'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='is_food',
            field=models.BooleanField(default=True),
        ),
    ]
