# Generated by Django 6.0.3 on 2026-03-07 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_meal_is_food'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='is_beverage',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='meal',
            name='quantity',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='meal',
            name='unit',
            field=models.CharField(default='unit', max_length=50),
        ),
    ]
