# Generated by Django 6.0.3 on 2026-03-07 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_meal_is_beverage_meal_quantity_meal_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='meal_type',
            field=models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('snack', 'Snack'), ('beverage', 'Beverage')], max_length=20),
        ),
    ]
